.TH WEATHERME 1 
.SH NAME
weatherme \- show weather from forecast.io 
.SH DESCRIPTION
.B weatherme
shows weather from forecast.io. It expects a forecast.io api key to be set via the KEY environment variable and for a latitude and longitude to be set via the LATLON environment variable. 
.SH SYNOPSIS
.B weatherme 
.RB [ \-c ]
.SH DESCRIPTION
.B weatherme
displays weather from forecast.io
.SH OPTIONS
.TP
.B \-c
display temperature in Celsius
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
See the package.json file in the distribution.

