.TH WEATHERME 1 
.SH NAME
weatherme \- show weather from forecast.io 
.SH SYNOPSIS
.B weatherme 
.RB [ \-u ]
.RB [ \-m ]
.RB [ \-h ]
.RB [ \-d ]
.RB [ \-s ]
.RB [ \-k 
.IR apikey ]
.RB [ \-l 
.IR latlon ]
.SH DESCRIPTION
.B weatherme
Weatherme shows data from forecast.io in the console. 
.SH OPTIONS
.TP
.B \-u " weatherme_units"
display temperature using forecase.io units i.e. us, uk, ca, si or auto based on LATLON. This may also be set by the WEATHERME_UNITS environment variable
.TP
.B \-m
display minutely data
.TP
.B \-h
display hourly data
.TP
.B \-d
display daily data
.TP
.B \-s
display only a summary
.TP
.BI \-k " apikey"
the forecast.io api key. This may also be set by the KEY environment variable
.TP
.BI \-l " latlon"
the long lat co-ordinates for the location. This may also be set by the LATLON environment variable
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH BUGS
See the package.json file in the distribution.

